name: 🚀 Build and Archive Website

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v2

      - name: 🗂️ Prepare Distribution Directory
        run: |
          mkdir -p dist/
          cp -R * dist/ # Kopiere alle Dateien im Root-Verzeichnis

      - name: 🚚 Exclude Non-Distributable Files
        run: |
          rm -rf dist/.git dist/.github dist/workflows # Entferne nicht benötigte Dateien und Verzeichnisse

      - name: 📦 Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
