name: 🚀 Build and Archive Website

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v2

      - name: 🗂️ Prepare Distribution Directory
        run: |
          mkdir -p dist/
          cp *.html dist/ # Kopiere alle HTML-Dateien
          cp *.css dist/ # Kopiere alle CSS-Dateien
          # Füge hier weitere Kopierbefehle hinzu für andere Dateitypen, die du benötigst, z.B. cp *.js dist/

      - name: 📦 Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
