name: 🚀 Build and Archive Nuxt.js Site

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v2

      - name: 🧶 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Oder eine andere Node-Version, die dein Projekt benötigt

      - name: 📦 Install Dependencies
        run: npm install
        working-directory: ./development/fw-frontend # Wechsle ins Frontend-Verzeichnis

      - name: ⚙️ Build Nuxt.js Project
        run: npm run build
        working-directory: ./development/fw-frontend # Wechsle ins Frontend-Verzeichnis

      - name: 🗂️ Prepare Archive
        run: |
          # Das generierte `dist` Verzeichnis von Nuxt.js befindet sich innerhalb des Frontend-Verzeichnisses
          cp -R ./development/fw-frontend/.nuxt/dist/client/ dist/ # Kopiere den Inhalt von `.nuxt/dist/client/` nach `dist/`
          # Falls du statische Dateien hast, die kopiert werden müssen, kannst du sie hier hinzufügen.
          # Zum Beispiel:
          # cp -R ./development/fw-frontend/static/* dist/

      - name: 📦 Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
