name: Build and Test Nuxt.js application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Verwenden Sie die empfohlene Node.js Version

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
      working-directory: ./development/fw-frontend  # Pfad zu Ihrem Nuxt.js Projekt
    - name: Build
      run: npm run build
      working-directory: ./development/fw-frontend  # Pfad zu Ihrem Nuxt.js Projekt
    - name: Run tests
      run: npm run test
      working-directory: ./development/fw-frontend  # Pfad zu Ihrem Nuxt.js Projekt
    - name: Generate Static Site (if needed)
      run: npm run generate
      working-directory: ./development/fw-frontend  # Pfad zu Ihrem Nuxt.js Projekt
