name: Nuxt.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Node-v18

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: INSTALLING DEPENDENCIES...
      run: npm ci
      working-directory: ./development/fw-frontend

    - name: LINT...
      run: npm run lint
      working-directory: ./development/fw-frontend
      continue-on-error: true # Optional, falls Linting-Fehler nicht den Prozess stoppen sollen

    - name: BUILDING...
      run: npm run build
      working-directory: ./development/fw-frontend

    - name: GENERATING STATIC SITE...
      run: npm run generate
      working-directory: ./development/fw-frontend
      
# Made by L5ON with <3
