name: 🚀 Nuxt.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Verwenden der neuesten stabilen Node-Version

    steps:
    - name: ✅ Checkout Code
      uses: actions/checkout@v3
      
    - name: 🌟 Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: 📦 Install Dependencies
      run: npm ci
      working-directory: ./development/fw-frontend

    - name: 🏗️ Build Project
      run: npm run build
      working-directory: ./development/fw-frontend

    - name: 🚚 Move Build to the Specific Directory
      run: |
        mkdir -p ./development/fw-frontend/build
        mv .nuxt/* ./development/fw-frontend/build/
      working-directory: ./development/fw-frontend

    - name: 📤 Upload Build Directory
      uses: actions/upload-artifact@v2
      with:
        name: build-directory
        path: ./development/fw-frontend/build/

    # Optional: Fügen Sie Schritte für Tests oder weitere Überprüfungen hinzu.
    # - name: 🧪 Run Tests
    #   run: npm test
    #   working-directory: ./development/fw-frontend

    # Optional: Fügen Sie Schritte hinzu, um den Build auf einen Server hochzuladen, wenn dies gewünscht wird.
    # - name: 🚀 Deploy to Server
    #   run: DEPLOY_SCRIPT_OR_COMMAND
    #   working-directory: ./development/fw-frontend/build/
