name: 🚀 Build and Archive Website

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v2
      
      - name: 📂 List directory structure
        run: ls -R # Zeigt die Struktur des ausgecheckten Repositories an

      - name: 🗂️ Prepare Distribution Directory
        run: |
          mkdir -p dist/
          cp src/*.html dist/ # Kopiere alle HTML-Dateien aus dem Verzeichnis 'src'
          cp src/*.css dist/ # Kopiere alle CSS-Dateien aus dem Verzeichnis 'src'
          # Füge hier weitere Kopierbefehle hinzu für andere Dateitypen, die du benötigst, z.B. cp src/*.js dist/

      - name: 📦 Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
